version: '2'
services:
  embulk:
    image: {{DOCKER_IMAGE}}
    environment:
      PLUGINS: "embulk-input-jdbc liquid"
      CONFIG: /etc/embulk/${LOWERCASE_TABLE_NAME}.yml.liquid
      LOG_LEVEL: info
      LOG_FILE_NAME: ETC_ORACLE_DWH_EXPORT_${FILE_SUBFIX}.log
      LOG_PATH: /opt/scripts/log/
    volumes:
      - {{LOCAL_BASEDIR}}/log:/opt/scripts/log
      - {{LOCAL_BASEDIR}}/yml/input:/etc/embulk
      - {{LOCAL_BASEDIR}}/work:/opt/scripts/data
