CREATE TABLE "HONTO2"."M_APCRD_MEM_TMP_MCH" 
   (	"APCRD_NO" CHAR(13 BYTE), 
	"MEM_ID" CHAR(10 BYTE), 
	"MCH_FLG" CHAR(1 BYTE), 
	"REG_DTTM" DATE, 
	"REG_USR_ID" VARCHAR2(32 BYTE), 
	"UPD_DTTM" DATE, 
	"UPD_USR_ID" VARCHAR2(32 BYTE), 
	"DAT_UPD_CLS" CHAR(1 BYTE), 
	"UPD_TMS" NUMBER(9,0), 
	"LGC_DEL_FLG" CHAR(1 BYTE)
   );

   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."APCRD_NO" IS 'アプリカード番号';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."MEM_ID" IS '会員ＩＤ';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."MCH_FLG" IS '紐付けフラグ';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."REG_DTTM" IS '登録日時';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."REG_USR_ID" IS '登録ユーザＩＤ';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."UPD_DTTM" IS '更新日時';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."UPD_USR_ID" IS '更新ユーザＩＤ';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."DAT_UPD_CLS" IS 'データ更新区分';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."UPD_TMS" IS '更新回数';
   COMMENT ON COLUMN "HONTO2"."M_APCRD_MEM_TMP_MCH"."LGC_DEL_FLG" IS '論理削除フラグ';
   COMMENT ON TABLE "HONTO2"."M_APCRD_MEM_TMP_MCH"  IS 'アプリカード会員仮紐付け';

