version: '2'
services:
  embulk:
    image: <DOCKER_IMAGE>
    environment:
      PLUGINS: "embulk-input-jdbc embulk-filter-eval embulk-filter-column liquid"
      CONFIG: /etc/embulk/m_apcrd_mem_tmp_mch.yml.liquid
      LOG_LEVEL: info
      LOG_FILE_NAME: EMBULK_ORACLE_DWH_EXPORT_<FILE_SUBFIX>.log
      LOG_PATH: /opt/scripts/log/
    volumes:
      - <LOCAL_BASEDIR>/log:/opt/scripts/log
      - <LOCAL_BASEDIR>/yml/input:/etc/embulk
      - <OUTPUT_DIR>:/opt/scripts/data
