version: '2'
services:
  embulk:
    image: <DOCKER_IMAGE>
    environment:
      PLUGINS: "embulk-input-oracle embulk-filter-typecast embulk-filter-ruby_proc liquid"
      CONFIG: /etc/embulk/<LOWERCASE_TABLE_NAME>.yml.liquid
      LOG_LEVEL: info
      LOG_FILE_NAME: EMBULK_ORACLE_DWH_EXPORT_<FILE_SUBFIX>.log
      LOG_PATH: /opt/scripts/log/
    volumes:
      - <LOCAL_BASEDIR>/log:/opt/scripts/log
      - <LOCAL_BASEDIR>/yml/input:/etc/embulk
      - <LOCAL_BASEDIR>:/opt/scripts/data
